class com.alessiomanai.gymregister.database.Query{
- int DATABASE_VERSION
- android.database.sqlite.SQLiteDatabase db
+ void Query (Context )
+ void onCreate (SQLiteDatabase )
+ void onUpgrade (SQLiteDatabase db, int oldVersion, int )
- java.lang.String creaTabellaIscritto ()
- java.lang.String creaTabellaCorso ()
- java.lang.String creaTabellaPresenze ()
- java.lang.String creaTabellaPagamento ()
- java.lang.String creaTabellaImporti ()
- java.lang.String creaTabellaCertificati ()
- java.lang.String aggiuntaAgostoPagamenti ()
- java.lang.String aggiuntaAgostoImporti ()
}
class android.database.sqlite.SQLiteOpenHelper{
+ void SQLiteOpenHelper (Context context, String name, CursorFactory factory, int )
+ void SQLiteOpenHelper (Context context, String name, CursorFactory factory, int version, DatabaseErrorHandler )
+ void SQLiteOpenHelper (Context context, String name, int version, OpenParams )
+ java.lang.String getDatabaseName ()
+ void setWriteAheadLoggingEnabled (boolean )
+ void setLookasideConfig (int slotSize, int )
+ void setOpenParams (OpenParams )
+ void setIdleConnectionTimeout (long )
+ android.database.sqlite.SQLiteDatabase getWritableDatabase ()
+ android.database.sqlite.SQLiteDatabase getReadableDatabase ()
+ void close ()
+ void onConfigure (SQLiteDatabase )
+ void onCreate (SQLiteDatabase )
+ void onUpgrade (SQLiteDatabase sqLiteDatabase, int i, int )
+ void onDowngrade (SQLiteDatabase db, int oldVersion, int )
+ void onOpen (SQLiteDatabase )
}
interface java.lang.AutoCloseable {
+ void close ()
}
java.lang.AutoCloseable <|.. android.database.sqlite.SQLiteOpenHelper
android.database.sqlite.SQLiteOpenHelper <|-- com.alessiomanai.gymregister.database.Query
class com.alessiomanai.gymregister.database.Tabelle{
+ void Tabelle ()
}
class com.alessiomanai.gymregister.database.QueryCorso{
- int DATABASE_VERSION
- android.database.sqlite.SQLiteDatabase db
+ void QueryCorso (Context )
+ void nuovo (Query context, Corso )
+ android.database.Cursor getCorso (Query )
+ java.util.ArrayList<com.alessiomanai.gymregister.classi.Corso> getElencoCorsi (Query )
+ boolean eliminaCorso (Query context, Corso )
+ boolean rinominaCorso (Query context, Corso corso, String )
}
class com.alessiomanai.gymregister.database.QueryImporti{
- int DATABASE_VERSION
- android.database.sqlite.SQLiteDatabase db
+ void QueryImporti (Context )
+ void inserisciImporti (Query context, Iscritto iscritto, Corso )
+ void updateImporti (Query context, Iscritto iscritto, Corso )
+ com.alessiomanai.gymregister.classi.Importi caricaImporti (Query context, Iscritto iscritto, Corso )
}
class com.alessiomanai.gymregister.database.QueryIscritto{
- java.lang.String[] iscritto
- int DATABASE_VERSION
- android.database.sqlite.SQLiteDatabase db
+ void QueryIscritto (Context )
+ void nuovo (Query context, Iscritto iscritto, Corso )
+ java.util.ArrayList<com.alessiomanai.gymregister.classi.Iscritto> caricaIscritti (Query context, Corso )
+ boolean aggiorna (Query context, Iscritto )
+ void elimina (Query context, Iscritto )
+ int selectLastIDIscritto (Query )
+ int selectLastIDCorso (Query )
+ java.util.ArrayList<com.alessiomanai.gymregister.classi.Iscritto> cercaIscritto (Query context, Corso id, String )
+ boolean salvaNoteFile (Query context, Iscritto )
+ boolean aggiornaFotoProfilo (Query context, Iscritto )
+ java.lang.String getUrlPhoto (Query context, Iscritto )
+ boolean cambiaCorsoUtente (Query context, Iscritto iscritto, Corso )
}
class com.alessiomanai.gymregister.database.QueryPresenze{
- int DATABASE_VERSION
- android.database.sqlite.SQLiteDatabase db
+ void QueryPresenze (Context )
+ android.database.Cursor getPresenze (Query )
+ java.util.ArrayList<com.alessiomanai.gymregister.classi.Presenza> presenzeIscritto (Query context, Iscritto )
+ java.util.ArrayList<com.alessiomanai.gymregister.classi.Presenza> presenzeIscrittoOrdineDecrescente (Query context, Iscritto )
+ java.util.ArrayList<com.alessiomanai.gymregister.classi.Presenza> presenzeCorso (Query context, Corso )
+ void aggiungi (Query context, Iscritto iscritto, Corso )
+ boolean eliminaPresenzaOdierna (Query context, Iscritto )
+ android.database.Cursor presenzeOdierneCursor (Query context, Corso )
+ java.util.ArrayList<com.alessiomanai.gymregister.classi.Presenza> presenzeOdierne (Query context, Corso )
+ boolean eliminaPresenzaVecchia (Query context, Iscritto iscritto, String )
+ void aggiungiPresenzaPrecedente (Query context, Iscritto iscritto, Corso corso, String )
+ java.util.ArrayList<com.alessiomanai.gymregister.classi.Presenza> presenzeCorsoMese (Query context, Iscritto iscritto, Corso corso, String )
}
class com.alessiomanai.gymregister.database.QueryPagamento{
- int DATABASE_VERSION
- android.database.sqlite.SQLiteDatabase db
+ void QueryPagamento (Context )
+ void inizializza (Query context, Iscritto iscritto, Corso )
+ void update (Query context, Iscritto )
+ android.database.Cursor getPagamenti (Query )
+ java.util.ArrayList<java.lang.String> utentiNotPay (Query context, String mese, String month, Corso )
}
class com.alessiomanai.gymregister.database.QueryCertificati{
- int DATABASE_VERSION
- android.database.sqlite.SQLiteDatabase db
+ void QueryCertificati (Context )
+ void nuovo (Query context, Iscritto iscritto, String )
+ java.lang.String getCertificatoMedico (Query context, Iscritto )
+ boolean certificatoExists (Query context, Iscritto )
+ void update (Query context, Iscritto iscritto, String )
}
class com.alessiomanai.gymregister.database.QueryPagamentoCustom{
- java.lang.String nomeTabella
- int DATABASE_VERSION
- android.database.sqlite.SQLiteDatabase db
+ void QueryPagamentoCustom (Context )
+ void creaNuovoPagamento (Query context, Corso corso, String )
+ void aggiornaPagamento (Query context, String pagamento, Iscritto iscritto, int )
+ java.util.ArrayList<java.lang.String> carica (Query context, Corso )
+ int caricaPagamentiIscritto (Query context, String pagamento, Iscritto )
}